In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
food_nutrients_data = pd.read_csv('/content/drive/MyDrive/OptumStratethon/NutritionFileFInal.csv')
food_nutrients_data

     Food Code  ... Vitamin C mg
0       17-215  ...          0.0
1      50-1094  ...          0.0
2       17-506  ...          0.0
3       17-221  ...          0.0
4       17-220  ...          0.0
...        ...  ...          ...
3418    13-283  ...          8.0
3419    13-284  ...          1.0
3420    13-285  ...          1.0
3421    13-317  ...        225.0
3422    13-272  ...          0.0

[3423 rows x 33 columns]

In [ ]:
!unzip -q '/content/drive/MyDrive/OptumStratethon.zip'

allergies_names = ['allergies_START', 'allergies_STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'allergies_DESCRIPTION']
allergies = pd.read_csv("/content/csv/allergies.csv", names=allergies_names)

careplans_names = ['careplans_Id', 'careplans_START', 'careplans_STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'careplans_DESCRIPTION','REASONCODE', 'REASONDESCRIPTION']
careplans = pd.read_csv("/content/csv/careplans.csv", names=careplans_names)
  
conditions_names = ['conditions_START', 'conditions_STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'conditions_DESCRIPTION']
conditions = pd.read_csv("/content/csv/conditions.csv", names = conditions_names)

devices_names = ['devices_START', 'devices_STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'devices_DESCRIPTION', 'UDI']
devices = pd.read_csv("/content/csv/devices.csv", names = devices_names)

encounters_names = ['ENCOUNTER', 'encounters_START', 'encounters_STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER','ENCOUNTERCLASS', 'CODE', 'encounters_DESCRIPTION', 
                      'BASE_ENCOUNTER_COST','TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'enc_REASONCODE','enc_REASONDESCRIPTION']
encounters = pd.read_csv("/content/csv/encounters.csv", names=encounters_names)

imaging_studies_names = ['IMAGING_STUDIES', 'is_DATE', 'PATIENT', 'ENCOUNTER', 'BODYSITE_CODE',
       'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION','SOP_CODE', 'SOP_DESCRIPTION']
imaging_studies = pd.read_csv("/content/csv/imaging_studies.csv", names = imaging_studies_names)

immunizations_names = ['immunization_DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'immunization_DESCRIPTION', 'immunization_BASE_COST']
immunizations = pd.read_csv("/content/csv/immunizations.csv", names = immunizations_names)

medications_names = ['meds_START', 'meds_STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'meds_CODE', 'meds_DESCRIPTION',
       'meds_BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'meds_REASONCODE','meds_REASONDESCRIPTION']
medications = pd.read_csv("/content/csv/medications.csv", names=medications_names)

observations_names = ['obs_DATE', 'PATIENT', 'ENCOUNTER', 'obs_CODE', 'obs_DESCRIPTION', 'VALUE', 'UNITS','TYPE']
observations = pd.read_csv("/content/csv/observations.csv", names=observations_names)

organizations_names = ['ORGANIZATIONS', 'org_NAME', 'org_ADDRESS', 'org_CITY', 'org_STATE', 'org_ZIP', 'org_LAT', 'org_LON', 'org_PHONE','org_REVENUE', 'org_UTILIZATION']
organizations = pd.read_csv("/content/csv/organizations.csv", names = organizations_names)

patients_names = ['PATIENT', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT','PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE',
     'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'pat_ADDRESS', 'pat_CITY', 'pat_STATE','pat_COUNTY', 'pat_ZIP', 'pat_LAT', 'pat_LON', 'HEALTHCARE_EXPENSES','HEALTHCARE_COVERAGE']
patients = pd.read_csv("/content/csv/patients.csv", names=patients_names)

payer_transitions_names = ['PATIENT', 'START_YEAR', 'END_YEAR', 'PAYER', 'OWNERSHIP']
payer_transitions = pd.read_csv("/content/csv/payer_transitions.csv", names=payer_transitions_names)

payers_names = ['PAYER', 'payer_NAME', 'payer_ADDRESS', 'payer_CITY', 'STATE_HEADQUARTERED', 'payer_ZIP', 'payer_PHONE',
       'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'payer_REVENUE', 'COVERED_ENCOUNTERS','UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS',
       'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS','UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG','MEMBER_MONTHS']
payers = pd.read_csv("/content/csv/payers.csv", names=payers_names)

procedures_names = ['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'procedure_DESCRIPTION', 'procedure_BASE_COST','REASONCODE', 'REASONDESCRIPTION']
procedures = pd.read_csv("/content/csv/procedures.csv", names=procedures_names)

providers_names = ['PROVIDER', 'ORGANIZATION', 'prov_NAME', 'prov_GENDER', 'SPECIALITY', 'prov_ADDRESS', 'prov_CITY',
       'prov_STATE', 'prov_ZIP', 'prov_LAT', 'prov_LON', 'prov_UTILIZATION']
providers = pd.read_csv("/content/csv/providers.csv", names = providers_names)

supplies = pd.read_csv("/content/csv/supplies.csv")

In [ ]:
patient_allergies = pd.merge(allergies, patients, on=['PATIENT'], how='right')
patient_allergies.drop(0, inplace=True)

patient_observations = pd.merge(observations, patients, on=['PATIENT'], how='right')
patient_observations.drop(0, inplace = True)

patient_conditions = pd.merge(conditions, patients, on=['PATIENT'], how='right')
patient_conditions.drop(0, inplace=True)

In [ ]:
patient_allergies

     allergies_START allergies_STOP  ... HEALTHCARE_EXPENSES HEALTHCARE_COVERAGE
1                NaN            NaN  ...           271227.08  1334.8799999999999
2                NaN            NaN  ...           793946.01             3204.49
3                NaN            NaN  ...            574111.9  2606.3999999999996
4                NaN            NaN  ...            935630.3   8756.189999999999
5                NaN            NaN  ...           598763.07              3772.2
...              ...            ...  ...                 ...                 ...
1623             NaN            NaN  ...          1622314.87  32086.309999999998
1624             NaN            NaN  ...           979724.25             3130.52
1625             NaN            NaN  ...          1560540.35            52391.24
1626             NaN            NaN  ...          1375833.47  13156.999999999998
1627             NaN            NaN  ...          1510158.34  26565.649999999998

[1627 rows x 30 columns]

In [ ]:
patient_allergies['allergies_DESCRIPTION'].value_counts()

Allergy to mould            81
Dander (animal) allergy     77
Allergy to tree pollen      63
House dust mite allergy     61
Allergy to grass pollen     60
Shellfish allergy           41
Allergy to bee venom        33
Allergy to nut              31
Allergy to fish             30
Allergy to peanuts          25
Allergy to wheat            25
Latex allergy               24
Allergy to eggs             20
Allergy to dairy product    18
Allergy to soya              8
Name: allergies_DESCRIPTION, dtype: int64

In [ ]:
patient_conditions

     conditions_START conditions_STOP  ... HEALTHCARE_EXPENSES HEALTHCARE_COVERAGE
1          2001-05-01             NaN  ...           271227.08  1334.8799999999999
2          2011-12-08      2011-12-22  ...           271227.08  1334.8799999999999
3          2019-03-20      2019-04-10  ...           271227.08  1334.8799999999999
4          2016-12-29      2017-01-05  ...           793946.01             3204.49
5          2011-05-13      2011-05-27  ...            574111.9  2606.3999999999996
...               ...             ...  ...                 ...                 ...
8391       1984-12-29             NaN  ...          1510158.34  26565.649999999998
8392       1988-08-24             NaN  ...          1510158.34  26565.649999999998
8393       2009-08-08             NaN  ...          1510158.34  26565.649999999998
8394       2010-11-18      2010-11-25  ...          1510158.34  26565.649999999998
8395       2012-04-23      2012-05-14  ...          1510158.34  26565.649999999998

[8395 rows x 30 columns]

In [ ]:
patient_conditions['conditions_DESCRIPTION'].unique()

array(['Chronic sinusitis (disorder)', 'Viral sinusitis (disorder)',
       'Acute bronchitis (disorder)', 'Laceration of foot',
       'Acute viral pharyngitis (disorder)',
       'Streptococcal sore throat (disorder)', 'Sprain of wrist',
       'Otitis media', 'Acute bacterial sinusitis (disorder)', nan,
       'Body mass index 30+ - obesity (finding)', 'Cystitis',
       'Fracture of forearm', 'Impacted molars', 'Normal pregnancy',
       'Sinusitis (disorder)', 'Anemia (disorder)',
       'Miscarriage in first trimester',
       'Fetus with unknown complication', 'Prediabetes', 'Hypertension',
       'Escherichia coli urinary tract infection',
       'Whiplash injury to neck', 'Atrial Fibrillation',
       'Sprain of ankle', 'Laceration of forearm',
       'Malignant neoplasm of breast (disorder)', 'Laceration of thigh',
       'Osteoarthritis of knee', 'Preeclampsia',
       'Perennial allergic rhinitis with seasonal variation',
       'Fracture of clavicle', 'Childhood asthma', 'Facial laceration',
       'Acute allergic reaction',
       'Concussion with no loss of consciousness',
       'Recurrent urinary tract infection', 'Hyperlipidemia',
       'Osteoarthritis of hip', 'Coronary Heart Disease',
       'Polyp of colon', 'Tubal pregnancy', 'Blighted ovum', 'Stroke',
       'Fracture of the vertebral column with spinal cord injury',
       'Atopic dermatitis', 'Seasonal allergic rhinitis',
       'Cardiac Arrest', 'History of cardiac arrest (situation)',
       'Fracture of ankle', 'Second degree burn',
       'Fracture subluxation of wrist', 'Diabetes',
       'Hypertriglyceridemia (disorder)',
       'Metabolic syndrome X (disorder)', 'Fracture of rib',
       'Antepartum eclampsia', 'Chronic pain',
       'Chronic intractable migraine without aura', 'Drug overdose',
       'Osteoporosis (disorder)', 'Idiopathic atrophic hypothyroidism',
       'Seizure disorder', 'History of single seizure (situation)',
       'Perennial allergic rhinitis', 'Epilepsy', 'Myocardial Infarction',
       'History of myocardial infarction (situation)',
       'Body mass index 40+ - severely obese (finding)',
       'Hyperglycemia (disorder)',
       'Neuropathy due to type 2 diabetes mellitus (disorder)',
       'Diabetic retinopathy associated with type II diabetes mellitus (disorder)',
       'Nonproliferative diabetic retinopathy due to type 2 diabetes mellitus (disorder)',
       'Chronic kidney disease stage 1 (disorder)',
       'Diabetic renal disease (disorder)',
       'Localized  primary osteoarthritis of the hand',
       'Neoplasm of prostate', 'Carcinoma in situ of prostate (disorder)',
       'Laceration of hand',
       'Injury of tendon of the rotator cuff of shoulder',
       'Pulmonary emphysema (disorder)', 'Appendicitis',
       'History of appendectomy', 'Major depression disorder',
       'Alcoholism', 'Burn injury(morphologic abnormality)',
       'Rupture of patellar tendon',
       'Concussion with loss of consciousness',
       'Child attention deficit disorder',
       'Injury of medial collateral ligament of knee',
       'Recurrent rectal polyp', 'Contact dermatitis',
       "Familial Alzheimer's disease of early onset (disorder)",
       'Chronic kidney disease stage 2 (disorder)',
       'Microalbuminuria due to type 2 diabetes mellitus (disorder)',
       'Bleeding from anus', 'Protracted diarrhea',
       'Malignant tumor of colon', 'Suspected lung cancer (situation)',
       'Non-small cell lung cancer (disorder)',
       'Non-small cell carcinoma of lung  TNM stage 1 (disorder)',
       'First degree burn', 'Chronic congestive heart failure (disorder)',
       'Chronic obstructive bronchitis (disorder)',
       'Tear of meniscus of knee',
       'Fracture of vertebral column without spinal cord injury',
       'Smokes tobacco daily', 'Gout', 'Rupture of appendix',
       "Alzheimer's disease (disorder)", 'Pneumonia',
       'Opioid abuse (disorder)', 'Concussion injury of brain',
       'Metastasis from malignant tumor of prostate (disorder)',
       'Closed fracture of hip', 'Rheumatoid arthritis',
       'Overlapping malignant neoplasm of colon',
       'Macular edema and retinopathy due to type 2 diabetes mellitus (disorder)',
       'Pathological fracture due to osteoporosis (disorder)',
       'Brain damage - traumatic',
       'Secondary malignant neoplasm of colon', 'Bullet wound',
       'Proliferative diabetic retinopathy due to type II diabetes mellitus (disorder)',
       'Injury of anterior cruciate ligament', 'Pyelonephritis',
       'Primary fibromyalgia syndrome',
       'Primary malignant neoplasm of colon',
       'Small cell carcinoma of lung (disorder)',
       'Primary small cell malignant neoplasm of lung  TNM stage 1 (disorder)',
       'Major depression  single episode'], dtype=object)

In [ ]:
patient_observations

                    obs_DATE  ... HEALTHCARE_COVERAGE
1       2011-07-28T15:02:18Z  ...  1334.8799999999999
2       2011-07-28T15:02:18Z  ...  1334.8799999999999
3       2011-07-28T15:02:18Z  ...  1334.8799999999999
4       2011-07-28T15:02:18Z  ...  1334.8799999999999
5       2011-07-28T15:02:18Z  ...  1334.8799999999999
...                      ...  ...                 ...
299693  2015-09-05T16:27:52Z  ...  26565.649999999998
299694  2016-09-05T16:27:52Z  ...  26565.649999999998
299695  2017-09-05T16:27:52Z  ...  26565.649999999998
299696  2018-09-05T16:27:52Z  ...  26565.649999999998
299697  2019-09-05T16:27:52Z  ...  26565.649999999998

[299697 rows x 32 columns]

In [ ]:
factors = ['Body Height', 'Body Weight', 'Body Mass Index', 
           'Diastolic Blood Pressure','Systolic Blood Pressure', 'Heart rate', 'Respiratory rate',
          'Body temperature', 'Leukocytes [#/volume] in Blood by Automated count', 'Erythrocytes [#/volume] in Blood by Automated count',
          'Hemoglobin [Mass/volume] in Blood',
          'Hematocrit [Volume Fraction] of Blood by Automated count',
          'MCV [Entitic volume] by Automated count',
          'MCH [Entitic mass] by Automated count',
          'MCHC [Mass/volume] by Automated count',
          'Total Cholesterol', 'Low Density Lipoprotein Cholesterol',
          'High Density Lipoprotein Cholesterol'
          'Urea Nitrogen', 'Creatinine', 'Calcium', 'Sodium', 'Potassium',
          'Chloride', 'Carbon Dioxide', 'Protein [Mass/volume] in Serum or Plasma',
          'Albumin [Mass/volume] in Serum or Plasma',
          'Globulin [Mass/volume] in Serum by calculation',
          'Bilirubin.total [Mass/volume] in Serum or Plasma',
          'Glucose [Mass/volume] in Urine by Test strip',
          'Bilirubin.total [Mass/volume] in Urine by Test strip',
          'Protein [Mass/volume] in Urine by Test strip',
          'pH of Urine by Test strip', 'Hemoglobin [Presence] in Urine by Test strip']

patient_observations.loc[patient_observations['obs_DESCRIPTION'].isin(factors)]

                    obs_DATE  ... HEALTHCARE_COVERAGE
1       2011-07-28T15:02:18Z  ...  1334.8799999999999
3       2011-07-28T15:02:18Z  ...  1334.8799999999999
4       2011-07-28T15:02:18Z  ...  1334.8799999999999
5       2011-07-28T15:02:18Z  ...  1334.8799999999999
6       2011-07-28T15:02:18Z  ...  1334.8799999999999
...                      ...  ...                 ...
299660  2019-07-13T17:27:52Z  ...  26565.649999999998
299661  2019-07-13T17:27:52Z  ...  26565.649999999998
299662  2019-07-13T17:27:52Z  ...  26565.649999999998
299663  2019-07-13T17:27:52Z  ...  26565.649999999998
299665  2019-07-13T17:27:52Z  ...  26565.649999999998

[167526 rows x 32 columns]

In [ ]:
required_data = patient_observations[['obs_DATE','PATIENT','ENCOUNTER', 'obs_CODE','PREFIX', 'FIRST', 'LAST', 'GENDER', 'BIRTHDATE', 'DEATHDATE','obs_DESCRIPTION', 'VALUE', 'UNITS']][patient_observations['obs_DESCRIPTION'].isin(factors)]
required_data

                    obs_DATE  ...   UNITS
1       2011-07-28T15:02:18Z  ...      cm
3       2011-07-28T15:02:18Z  ...      kg
4       2011-07-28T15:02:18Z  ...   kg/m2
5       2011-07-28T15:02:18Z  ...  mm[Hg]
6       2011-07-28T15:02:18Z  ...  mm[Hg]
...                      ...  ...     ...
299660  2019-07-13T17:27:52Z  ...  mm[Hg]
299661  2019-07-13T17:27:52Z  ...    /min
299662  2019-07-13T17:27:52Z  ...    /min
299663  2019-07-13T17:27:52Z  ...   mg/dL
299665  2019-07-13T17:27:52Z  ...   mg/dL

[167526 rows x 13 columns]

In [ ]:
required_data[required_data['obs_DESCRIPTION']=='High Density Lipoprotein Cholesterol']

Empty DataFrame
Columns: [obs_DATE, PATIENT, ENCOUNTER, obs_CODE, PREFIX, FIRST, LAST, GENDER, BIRTHDATE, DEATHDATE, obs_DESCRIPTION, VALUE, UNITS]
Index: []

In [ ]:
units = {}
for ind in required_data.index:
  units[required_data['obs_DESCRIPTION'][ind]] = required_data['UNITS'][ind]
units

{'Albumin [Mass/volume] in Serum or Plasma': 'g/dL',
 'Bilirubin.total [Mass/volume] in Serum or Plasma': 'mg/dL',
 'Bilirubin.total [Mass/volume] in Urine by Test strip': 'mg/dL',
 'Body Height': 'cm',
 'Body Mass Index': 'kg/m2',
 'Body Weight': 'kg',
 'Body temperature': 'Cel',
 'Calcium': 'mg/dL',
 'Carbon Dioxide': 'mmol/L',
 'Chloride': 'mmol/L',
 'Creatinine': 'mg/dL',
 'Diastolic Blood Pressure': 'mm[Hg]',
 'Erythrocytes [#/volume] in Blood by Automated count': '10*6/uL',
 'Globulin [Mass/volume] in Serum by calculation': 'g/L',
 'Glucose [Mass/volume] in Urine by Test strip': 'mg/dL',
 'Heart rate': '/min',
 'Hematocrit [Volume Fraction] of Blood by Automated count': '%',
 'Hemoglobin [Mass/volume] in Blood': 'g/dL',
 'Hemoglobin [Presence] in Urine by Test strip': '{nominal}',
 'Leukocytes [#/volume] in Blood by Automated count': '10*3/uL',
 'Low Density Lipoprotein Cholesterol': 'mg/dL',
 'MCH [Entitic mass] by Automated count': 'pg',
 'MCHC [Mass/volume] by Automated count': 'g/dL',
 'MCV [Entitic volume] by Automated count': 'fL',
 'Potassium': 'mmol/L',
 'Protein [Mass/volume] in Serum or Plasma': 'g/dL',
 'Protein [Mass/volume] in Urine by Test strip': 'mg/dL',
 'Respiratory rate': '/min',
 'Sodium': 'mmol/L',
 'Systolic Blood Pressure': 'mm[Hg]',
 'Total Cholesterol': 'mg/dL',
 'pH of Urine by Test strip': 'pH'}

In [ ]:
cols = ['DATE', 'PATIENT', 'ENCOUNTER', 'obs_CODE', 'PREFIX', 'FIRST', 'LAST', 'GENDER', 'BIRTHDATE', 'DEATHDATE',
        'Body Height' + "  " + units['Body Height'],  'Body Weight' + "  " + units['Body Weight'],
        'Body Mass Index' + "  " + units['Body Mass Index'], 'Body temperature' + "  " + units['Body temperature'],
        'Calcium'+"  "+units['Calcium'], 'Carbon Dioxide'+"  "+units['Carbon Dioxide'], 
        'Creatinine'+"  "+units['Creatinine'],  'Potassium'+"  "+units['Potassium'],  'Sodium'+"  "+units['Sodium'],
        'Heart rate'+"  "+units['Heart rate'],  'Respiratory rate'+"  "+units['Respiratory rate'],
        'Total Cholesterol'+"  "+units['Total Cholesterol'],
        'Low Density Lipoprotein Cholesterol'+"  "+units['Low Density Lipoprotein Cholesterol'],
        'Protein [Mass/volume] in Serum or Plasma'+"  "+units['Protein [Mass/volume] in Serum or Plasma'],
        'Protein [Mass/volume] in Urine by Test strip'+"  "+units['Protein [Mass/volume] in Urine by Test strip'],
        'Systolic Blood Pressure'+"  "+units['Systolic Blood Pressure'],
        'Diastolic Blood Pressure'+"  "+units['Diastolic Blood Pressure'],
        'Glucose [Mass/volume] in Urine by Test strip'+"  "+units['Glucose [Mass/volume] in Urine by Test strip'],
        'Hemoglobin [Mass/volume] in Blood'+"  "+units['Hemoglobin [Mass/volume] in Blood'],
        'Hematocrit [Volume Fraction] of Blood by Automated count'+"  "+units['Hematocrit [Volume Fraction] of Blood by Automated count'],
        'MCH [Entitic mass] by Automated count'+"  "+units['MCH [Entitic mass] by Automated count'],
        'MCHC [Mass/volume] by Automated count'+"  "+units['MCHC [Mass/volume] by Automated count'],
        'MCV [Entitic volume] by Automated count'+"  "+units['MCV [Entitic volume] by Automated count'],
        'Leukocytes [#/volume] in Blood by Automated count'+"  "+units['Leukocytes [#/volume] in Blood by Automated count'],
        'Erythrocytes [#/volume] in Blood by Automated count'+"  "+units['Erythrocytes [#/volume] in Blood by Automated count'],
        'Globulin [Mass/volume] in Serum by calculation'+"  "+units['Globulin [Mass/volume] in Serum by calculation'],
        'Albumin [Mass/volume] in Serum or Plasma' + "  " + units['Albumin [Mass/volume] in Serum or Plasma'],
        'Bilirubin.total [Mass/volume] in Serum or Plasma' +"  " + units['Bilirubin.total [Mass/volume] in Serum or Plasma'],
        'pH of Urine by Test strip'+"  "+units['pH of Urine by Test strip']
        ]

patient_df = pd.DataFrame(columns=cols)
patient_df

Empty DataFrame
Columns: [DATE, PATIENT, ENCOUNTER, obs_CODE, PREFIX, FIRST, LAST, GENDER, BIRTHDATE, DEATHDATE, Body Height  cm, Body Weight  kg, Body Mass Index  kg/m2, Body temperature  Cel, Calcium  mg/dL, Carbon Dioxide  mmol/L, Creatinine  mg/dL, Potassium  mmol/L, Sodium  mmol/L, Heart rate  /min, Respiratory rate  /min, Total Cholesterol  mg/dL, Low Density Lipoprotein Cholesterol  mg/dL, Protein [Mass/volume] in Serum or Plasma  g/dL, Protein [Mass/volume] in Urine by Test strip  mg/dL, Systolic Blood Pressure  mm[Hg], Diastolic Blood Pressure  mm[Hg], Glucose [Mass/volume] in Urine by Test strip  mg/dL, Hemoglobin [Mass/volume] in Blood  g/dL, Hematocrit [Volume Fraction] of Blood by Automated count  %, MCH [Entitic mass] by Automated count  pg, MCHC [Mass/volume] by Automated count  g/dL, MCV [Entitic volume] by Automated count  fL, Leukocytes [#/volume] in Blood by Automated count  10*3/uL, Erythrocytes [#/volume] in Blood by Automated count  10*6/uL, Globulin [Mass/volume] in Serum by calculation  g/L, Albumin [Mass/volume] in Serum or Plasma  g/dL, Bilirubin.total [Mass/volume] in Serum or Plasma  mg/dL, pH of Urine by Test strip  pH]
Index: []

In [ ]:
grouped_patients = required_data.groupby('PATIENT')

for name, group in grouped_patients:
  data_dict = {}
  data_dict['PATIENT'] = name
  for ind in group.index:
    data_dict['DATE'] = group['obs_DATE'][ind]
    data_dict['ENCOUNTER'] = group['ENCOUNTER'][ind]
    data_dict['obs_CODE'] = group['obs_CODE'][ind]
    data_dict['PREFIX'] = group['PREFIX'][ind]
    data_dict['FIRST'] = group['FIRST'][ind]
    data_dict['LAST'] = group['LAST'][ind]
    data_dict['GENDER'] = group['GENDER'][ind]
    data_dict['BIRTHDATE'] = group['BIRTHDATE'][ind]
    data_dict['DEATHDATE'] = group['DEATHDATE'][ind]
    #print(group['obs_DESCRIPTION'][ind] + "  " + units[group['obs_DESCRIPTION'][ind]])
    data_dict[group['obs_DESCRIPTION'][ind] + "  " + units[group['obs_DESCRIPTION'][ind]]] = group['VALUE'][ind]
  patient_df = patient_df.append(data_dict, ignore_index=True)
patient_df

                      DATE  ... Hemoglobin [Presence] in Urine by Test strip  {nominal}
0     2019-12-31T15:06:37Z  ...                                                NaN
1     2019-12-05T23:31:38Z  ...                                                NaN
2     2020-03-19T00:15:54Z  ...                                                NaN
3     2019-08-11T04:32:14Z  ...                                                NaN
4     2020-04-22T06:27:24Z  ...                                                NaN
...                    ...  ...                                                ...
1166  2019-11-06T17:10:39Z  ...                                                NaN
1167  2019-08-06T19:29:08Z  ...                                                NaN
1168  2019-07-29T10:57:26Z  ...                                                NaN
1169  2001-01-17T12:00:58Z  ...                                                NaN
1170  2019-11-18T09:02:32Z  ...                                                NaN

[1171 rows x 42 columns]

In [ ]:
payer_transitions

                                   PATIENT  ...  OWNERSHIP
0                                  PATIENT  ...  OWNERSHIP
1     1d604da9-9a81-4ba9-80c2-de3375d59b40  ...   Guardian
2     034e9e3b-2def-4559-bb2a-7850888ae060  ...   Guardian
3     8d4c4326-e9de-4f45-9a4c-f8c36bff89ae  ...   Guardian
4     8d4c4326-e9de-4f45-9a4c-f8c36bff89ae  ...       Self
...                                    ...  ...        ...
3797  fc817953-cc8b-45db-9c85-7c0ced8fa90d  ...       Self
3798  fc817953-cc8b-45db-9c85-7c0ced8fa90d  ...     Spouse
3799  fc817953-cc8b-45db-9c85-7c0ced8fa90d  ...     Spouse
3800  fc817953-cc8b-45db-9c85-7c0ced8fa90d  ...     Spouse
3801  fc817953-cc8b-45db-9c85-7c0ced8fa90d  ...     Spouse

[3802 rows x 5 columns]

In [ ]:
patient_df.to_csv('PatientsData.csv')

In [ ]:
patient_df.columns

Index(['DATE', 'PATIENT', 'ENCOUNTER', 'obs_CODE', 'PREFIX', 'FIRST', 'LAST',
       'GENDER', 'BIRTHDATE', 'DEATHDATE', 'Body Height  cm',
       'Body Weight  kg', 'Body Mass Index  kg/m2', 'Body temperature  Cel',
       'Calcium  mg/dL', 'Carbon Dioxide  mmol/L', 'Creatinine  mg/dL',
       'Potassium  mmol/L', 'Sodium  mmol/L', 'Heart rate  /min',
       'Respiratory rate  /min', 'Total Cholesterol  mg/dL',
       'Low Density Lipoprotein Cholesterol  mg/dL',
       'Protein [Mass/volume] in Serum or Plasma  g/dL',
       'Protein [Mass/volume] in Urine by Test strip  mg/dL',
       'Systolic Blood Pressure  mm[Hg]', 'Diastolic Blood Pressure  mm[Hg]',
       'Glucose [Mass/volume] in Urine by Test strip  mg/dL',
       'Hemoglobin [Mass/volume] in Blood  g/dL',
       'Hematocrit [Volume Fraction] of Blood by Automated count  %',
       'MCH [Entitic mass] by Automated count  pg',
       'MCHC [Mass/volume] by Automated count  g/dL',
       'MCV [Entitic volume] by Automated count  fL',
       'Leukocytes [#/volume] in Blood by Automated count  10*3/uL',
       'Erythrocytes [#/volume] in Blood by Automated count  10*6/uL',
       'Globulin [Mass/volume] in Serum by calculation  g/L',
       'Albumin [Mass/volume] in Serum or Plasma  g/dL',
       'Bilirubin.total [Mass/volume] in Serum or Plasma  mg/dL',
       'pH of Urine by Test strip  pH', 'Chloride  mmol/L',
       'Bilirubin.total [Mass/volume] in Urine by Test strip  mg/dL',
       'Hemoglobin [Presence] in Urine by Test strip  {nominal}'],
      dtype='object')

In [ ]:
food_nutrients_data.columns

Index(['Food Code', 'Food Name', 'Description', 'Group', 'Water g',
       'Protein g', 'Carbohydrate g', 'Sodium mg', 'Potassium mg',
       'Calcium mg', 'Magnesium mg', 'Phosphorus mg', 'Iron mg', 'Copper mg',
       'Zinc mg', 'Chloride mg', 'Manganese mg', 'Total sugars g',
       'Selenium µg', 'Iodine µg', 'Retinol µg', 'Vitamin D µg',
       'Vitamin E mg', 'Vitamin K1 µg', 'Thiamin mg', 'Riboflavin mg',
       '0yptophan/60 mg', 'Vitamin B6 mg', 'Vitamin B12 µg', 'Folate µg',
       'Pantothenate mg', 'Biotin µg', 'Vitamin C mg'],
      dtype='object')

In [ ]:
patient_df['Chloride  mmol/L'].unique()

array([nan, '101.9', '108.3', '104.3', '110.1', '104.6', '106.6', '102.2',
       '108.1', '101.1', '103.6', '104.8', '110.6', '102.4', '103.8',
       '108.2', '104.0', '106.0', '105.2', '106.7', '108.6', '108.5',
       '101.6', '110.5', '108.7', '101.3', '105.0', '106.5', '108.0',
       '107.0', '103.7', '110.9', '107.1', '109.7', '104.5', '104.1',
       '109.3', '105.8', '108.8', '101.5', '102.7', '109.9', '110.4',
       '107.5', '103.9', '101.8', '110.0', '111.0', '105.1', '102.1',
       '109.4', '106.3', '102.0', '109.0', '101.7', '104.4', '105.6',
       '104.9', '102.9', '102.8', '109.5', '104.2', '109.8', '107.4',
       '107.9', '108.4', '107.3', '110.7', '106.9', '110.8', '104.7',
       '102.3', '102.6', '109.1', '108.9', '105.7', '106.4', '105.4',
       '105.9', '107.2', '107.7', '106.8', '103.0', '103.2', '109.2',
       '103.1', '101.4', '106.1', '101.2', '103.4', '106.2', '105.3',
       '103.5', '102.5', '107.8', '110.2', '110.3', '103.3', '107.6'],
      dtype=object)

In [ ]:
patient_df['Calcium  mg/dL'].unique()

array([nan, '9.0', '9.4', '9.9', '8.8', '9.1', '9.2', '10.0', '9.5',
       '8.6', '8.9', '9.3', '9.6', '9.7', '9.8', '8.5', '8.7', '10.1',
       '10.2'], dtype=object)

In [ ]:
patient_df['Sodium  mmol/L'].unique()

array([nan, '139.6', '141.3', '138.0', '139.5', '141.0', '140.9', '141.2',
       '140.2', '138.5', '137.7', '143.4', '143.3', '139.2', '142.9',
       '139.3', '137.2', '138.1', '143.0', '140.0', '141.1', '137.6',
       '143.7', '138.4', '144.0', '143.5', '143.8', '140.8', '140.6',
       '139.8', '140.1', '142.8', '136.1', '142.5', '137.9', '140.3',
       '137.8', '136.7', '138.8', '141.9', '140.4', '136.9', '139.0',
       '136.8', '142.3', '136.6', '142.4', '141.6', '136.2', '136.5',
       '142.6', '140.5', '143.6', '137.1', '143.1', '138.3', '142.2',
       '137.4', '138.7', '136.3', '139.4', '142.1', '141.7', '139.9',
       '136.0', '142.7', '137.0', '138.9', '137.5', '138.6', '138.2',
       '140.7', '143.2', '139.7', '143.9', '139.1', '136.4', '141.4',
       '141.5', '141.8', '142.0', '137.3'], dtype=object)

In [ ]:
patient_df['Potassium  mmol/L'].unique()

array([nan, '4.6', '3.7', '3.9', '4.8', '4.3', '3.8', '5.2', '4.2', '4.4',
       '5.0', '4.7', '5.1', '4.1', '4.5', '4.0', '4.9'], dtype=object)

In [ ]:
allergies['allergies_DESCRIPTION'].unique()

array(['DESCRIPTION', 'Latex allergy', 'Shellfish allergy',
       'Allergy to mould', 'Dander (animal) allergy',
       'Allergy to grass pollen', 'Allergy to tree pollen',
       'Allergy to soya', 'Allergy to fish', 'House dust mite allergy',
       'Allergy to eggs', 'Allergy to wheat', 'Allergy to peanuts',
       'Allergy to dairy product', 'Allergy to nut',
       'Allergy to bee venom'], dtype=object)

In [ ]:
patient_df['Protein [Mass/volume] in Serum or Plasma  g/dL'].unique()

array([nan, '71.6', '60.6', '78.7', '79.3', '78.5', '79.5', '62.6',
       '68.9', '67.1', '63.5', '62.8', '71.0', '70.8', '63.9', '69.9',
       '69.6', '79.8', '60.7', '68.4', '69.0', '75.7', '62.1', '73.5',
       '65.5', '72.3', '73.0', '75.0', '66.8', '70.5', '78.1', '60.3',
       '75.2', '61.1', '75.3', '68.7', '73.2', '61.3', '61.4', '66.9',
       '65.1', '68.3', '76.8', '73.9', '62.9', '63.6', '76.1', '60.5',
       '63.8', '75.6', '69.1', '64.8', '66.7', '80.0', '72.7', '78.6',
       '67.6', '79.4', '67.7', '77.9', '62.7', '68.8', '61.6', '79.9',
       '62.5', '78.8', '74.8', '77.8', '69.5', '60.0', '69.4', '74.5',
       '71.8', '64.3', '77.5', '64.5', '66.0', '65.6', '67.8', '76.5',
       '76.9', '67.0', '60.4', '64.0', '78.9', '61.5', '65.0', '69.3',
       '63.7', '72.2', '72.1', '66.3', '65.4', '70.7', '72.6', '69.7',
       '78.4', '63.0', '64.6', '73.3', '64.7', '71.3', '68.2', '79.2',
       '72.8', '70.6', '73.6', '65.8', '69.8', '76.0', '72.0', '60.2',
       '74.1', '78.3', '61.8', '64.4', '60.9', '79.1', '70.0', '79.0',
       '60.8', '77.6', '66.5', '61.2', '70.1', '73.4', '74.4', '61.7',
       '65.9', '76.4', '77.1'], dtype=object)

In [ ]:
patient_df['Protein [Mass/volume] in Urine by Test strip  mg/dL'].unique()

array([nan, '55.8', '391.3', '348.4', '445.3', '411.9', '379.5', '255.8',
       '286.0', '324.4', '326.3', '348.8', '325.4', '335.5', '384.7',
       '303.1', '384.2', '278.3', '331.1', '382.2', '299.2', '244.6',
       '416.6', '62.2', '341.6', '256.1', '350.9', '279.1', '147.8',
       '321.7', '71.7', '56.7', '289.7', '286.5', '142.0', '115.0'],
      dtype=object)

In [ ]:
conditions['conditions_DESCRIPTION'].value_counts()

Viral sinusitis (disorder)                                               1248
Acute viral pharyngitis (disorder)                                        653
Acute bronchitis (disorder)                                               563
Normal pregnancy                                                          516
Body mass index 30+ - obesity (finding)                                   449
                                                                         ...
Primary small cell malignant neoplasm of lung  TNM stage 1 (disorder)       1
Pyelonephritis                                                              1
Fracture of vertebral column without spinal cord injury                     1
Fracture of the vertebral column with spinal cord injury                    1
Primary malignant neoplasm of colon                                         1
Name: conditions_DESCRIPTION, Length: 130, dtype: int64

In [ ]:
conditions.columns

Index(['conditions_START', 'conditions_STOP', 'PATIENT', 'ENCOUNTER', 'CODE',
       'conditions_DESCRIPTION'],
      dtype='object')

In [ ]:
careplans_names = ['careplans_Id', 'careplans_START', 'careplans_STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'careplans_DESCRIPTION','REASONCODE', 'REASONDESCRIPTION']
careplans = pd.read_csv("/content/csv/careplans.csv", names=careplans_names)
careplans.drop(0, inplace=True)
careplans['careplans_DESCRIPTION'].unique()

array(['Respiratory therapy', 'Wound care', 'Physical therapy procedure',
       'Urinary tract infection care', 'Fracture care',
       'Routine antenatal care', 'Diabetes self management plan',
       'Lifestyle education regarding hypertension',
       'Self-care interventions (procedure)', 'Musculoskeletal care',
       'Minor surgery care management (procedure)',
       'Asthma self management', 'Allergic disorder monitoring',
       'Head injury rehabilitation',
       'Hyperlipidemia clinical management plan', 'Skin condition care',
       'Burn care', 'Care plan (record artifact)', 'Cancer care plan',
       'Chronic obstructive pulmonary disease clinical management plan',
       'Mental health care plan', 'Care Plan',
       'Overactivity/inattention behavior management',
       'Demential management', 'Major surgery care management',
       'Terminal care', 'Heart failure self management plan',
       'Inpatient care plan (record artifact)',
       'Spinal cord injury rehabilitation',
       'Dialysis care plan (record artifact)', 'Psychiatry care plan',
       'Major depressive disorder clinical management plan'], dtype=object)

In [ ]:
careplans.head(10)

                            careplans_Id  ...            REASONDESCRIPTION
1   d2500b8c-e830-433a-8b9d-368d30741520  ...  Acute bronchitis (disorder)
2   07d9ddd8-dfa1-4e43-9bfe-39f63f4ace15  ...  Acute bronchitis (disorder)
3   a3bb6e99-3b99-44b3-974c-e230b4511b5c  ...  Acute bronchitis (disorder)
4   9f5284b7-425a-486a-b36e-ab818c018f2f  ...  Acute bronchitis (disorder)
5   47ede16c-c216-4f81-a16b-0e858de9cdc3  ...           Laceration of foot
6   7855c5ad-642b-4e64-b4d6-01265534ea84  ...  Acute bronchitis (disorder)
7   639c3ccd-8fc3-41a5-8f22-ffa04ce9a204  ...              Sprain of wrist
8   e91974f4-7455-4f84-9b28-63fc98068102  ...  Acute bronchitis (disorder)
9   c9a181dc-4f26-4b6f-8132-39ab44c5a6c9  ...  Acute bronchitis (disorder)
10  a2630b06-53c1-469a-9226-21ada6ef9816  ...                     Cystitis

[10 rows x 9 columns]

In [ ]:
conditions['conditions_DESCRIPTION'].unique()

array(['DESCRIPTION', 'Chronic sinusitis (disorder)',
       'Viral sinusitis (disorder)', 'Acute viral pharyngitis (disorder)',
       'Acute bronchitis (disorder)',
       'Streptococcal sore throat (disorder)', 'Laceration of foot',
       'Acute bacterial sinusitis (disorder)', 'Sprain of wrist',
       'Otitis media', 'Body mass index 30+ - obesity (finding)',
       'Cystitis', 'Fracture of forearm', 'Impacted molars',
       'Normal pregnancy', 'Sinusitis (disorder)', 'Anemia (disorder)',
       'Miscarriage in first trimester',
       'Fetus with unknown complication', 'Prediabetes', 'Hypertension',
       'Escherichia coli urinary tract infection',
       'Whiplash injury to neck', 'Atrial Fibrillation',
       'Sprain of ankle', 'Laceration of forearm',
       'Malignant neoplasm of breast (disorder)', 'Laceration of thigh',
       'Osteoarthritis of knee', 'Preeclampsia',
       'Perennial allergic rhinitis with seasonal variation',
       'Fracture of clavicle', 'Childhood asthma', 'Facial laceration',
       'Acute allergic reaction',
       'Concussion with no loss of consciousness',
       'Recurrent urinary tract infection', 'Hyperlipidemia',
       'Osteoarthritis of hip', 'Coronary Heart Disease',
       'Polyp of colon', 'Tubal pregnancy', 'Blighted ovum', 'Stroke',
       'Fracture of the vertebral column with spinal cord injury',
       'Atopic dermatitis', 'Seasonal allergic rhinitis',
       'Cardiac Arrest', 'History of cardiac arrest (situation)',
       'Fracture of ankle', 'Second degree burn',
       'Fracture subluxation of wrist', 'Diabetes',
       'Hypertriglyceridemia (disorder)',
       'Metabolic syndrome X (disorder)', 'Fracture of rib',
       'Antepartum eclampsia', 'Chronic pain',
       'Chronic intractable migraine without aura', 'Drug overdose',
       'Osteoporosis (disorder)', 'Idiopathic atrophic hypothyroidism',
       'Seizure disorder', 'History of single seizure (situation)',
       'Perennial allergic rhinitis', 'Epilepsy', 'Myocardial Infarction',
       'History of myocardial infarction (situation)',
       'Body mass index 40+ - severely obese (finding)',
       'Hyperglycemia (disorder)',
       'Neuropathy due to type 2 diabetes mellitus (disorder)',
       'Diabetic retinopathy associated with type II diabetes mellitus (disorder)',
       'Nonproliferative diabetic retinopathy due to type 2 diabetes mellitus (disorder)',
       'Chronic kidney disease stage 1 (disorder)',
       'Diabetic renal disease (disorder)',
       'Localized  primary osteoarthritis of the hand',
       'Neoplasm of prostate', 'Carcinoma in situ of prostate (disorder)',
       'Laceration of hand',
       'Injury of tendon of the rotator cuff of shoulder',
       'Pulmonary emphysema (disorder)', 'Appendicitis',
       'History of appendectomy', 'Major depression disorder',
       'Alcoholism', 'Burn injury(morphologic abnormality)',
       'Rupture of patellar tendon',
       'Concussion with loss of consciousness',
       'Child attention deficit disorder',
       'Injury of medial collateral ligament of knee',
       'Recurrent rectal polyp', 'Contact dermatitis',
       "Familial Alzheimer's disease of early onset (disorder)",
       'Chronic kidney disease stage 2 (disorder)',
       'Microalbuminuria due to type 2 diabetes mellitus (disorder)',
       'Bleeding from anus', 'Protracted diarrhea',
       'Malignant tumor of colon', 'First degree burn',
       'Suspected lung cancer (situation)',
       'Non-small cell lung cancer (disorder)',
       'Non-small cell carcinoma of lung  TNM stage 1 (disorder)',
       'Chronic congestive heart failure (disorder)',
       'Chronic obstructive bronchitis (disorder)',
       'Tear of meniscus of knee',
       'Fracture of vertebral column without spinal cord injury',
       'Smokes tobacco daily', 'Gout', 'Rupture of appendix',
       "Alzheimer's disease (disorder)", 'Pneumonia',
       'Opioid abuse (disorder)', 'Concussion injury of brain',
       'Metastasis from malignant tumor of prostate (disorder)',
       'Closed fracture of hip', 'Rheumatoid arthritis',
       'Overlapping malignant neoplasm of colon',
       'Macular edema and retinopathy due to type 2 diabetes mellitus (disorder)',
       'Pathological fracture due to osteoporosis (disorder)',
       'Brain damage - traumatic',
       'Secondary malignant neoplasm of colon', 'Bullet wound',
       'Proliferative diabetic retinopathy due to type II diabetes mellitus (disorder)',
       'Injury of anterior cruciate ligament', 'Pyelonephritis',
       'Primary fibromyalgia syndrome',
       'Primary malignant neoplasm of colon',
       'Small cell carcinoma of lung (disorder)',
       'Primary small cell malignant neoplasm of lung  TNM stage 1 (disorder)',
       'Major depression  single episode'], dtype=object)

In [ ]:
patient_df['Body Mass Index  kg/m2'].unique()

array(['20.6', '15.9', '28.1', '29.8', nan, '45.6', '30.2', '27.2',
       '29.2', '27.9', '19.1', '30.4', '23.5', '27.8', '21.0', '27.0',
       '27.4', '25.7', '29.3', '21.6', '28.3', '28.2', '20.4', '24.4',
       '16.8', '30.5', '31.8', '27.5', '27.7', '28.8', '28.6', '25.5',
       '21.4', '15.3', '32.6', '26.4', '16.5', '33.6', '22.1', '25.4',
       '26.8', '21.8', '16.7', '16.3', '25.0', '26.6', '29.7', '28.7',
       '17.9', '22.3', '29.4', '32.4', '27.6', '14.3', '30.3', '18.7',
       '28.9', '27.3', '24.3', '29.6', '29.5', '19.4', '28.0', '26.7',
       '28.4', '30.1', '17.7', '26.9', '26.5', '20.0', '22.2', '19.9',
       '28.5', '30.0', '16.2', '23.1', '25.1', '20.3', '27.1', '18.3',
       '14.1', '15.7', '16.6', '38.5', '30.6', '23.3', '15.4', '25.6',
       '18.8', '31.1', '17.3', '22.5', '32.8', '24.8', '29.0', '29.1',
       '24.2', '48.5', '23.7', '22.6', '16.4', '32.9', '15.6', '23.8',
       '42.6', '20.9', '31.5', '24.0', '36.5', '18.0', '20.1', '41.3',
       '23.2', '18.4', '21.3', '23.4', '23.9', '18.9', '17.6', '31.2',
       '26.1', '25.2', '25.9', '25.3', '26.2', '21.5', '15.5', '32.0',
       '19.8', '34.6', '22.7', '21.7', '24.6', '30.7', '18.1', '26.3',
       '16.9', '14.6', '22.8', '19.7', '25.8', '34.5', '24.1', '23.0',
       '16.0', '20.5', '14.9', '19.5', '34.2', '21.9', '42.9', '19.0',
       '17.4', '31.0', '19.3', '30.9', '17.8', '17.2', '29.9', '24.7',
       '36.3', '31.6', '22.9', '17.5', '41.0', '33.4', '18.2', '31.4',
       '32.1', '20.8', '36.9', '18.5', '14.7', '14.8', '21.1', '31.3',
       '37.3', '15.8', '24.5', '41.6', '20.2', '16.1', '33.9', '14.2',
       '13.7', '31.7', '22.4', '13.9', '13.8', '14.4', '15.2', '34.1',
       '17.1', '19.2', '24.9', '32.7', '26.0', '34.8'], dtype=object)